import type { Metadata } from "next";
import { QueryClientProviderCustom } from "@/providers/query-client";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/shared/components/organisms/app-sidebar/app-sidebar";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SidebarProvider>
          <QueryClientProviderCustom>
            <AppSidebar />
            <main className="w-full px-16 pt-8">
              {children}
            </main>
          </QueryClientProviderCustom>
        </SidebarProvider>
      </body>
    </html>
  );
}
